"""Read and write artifacts as human-reviewable JSON on disk.

JSON, not a binary or pickled format, because review is a first-class step in this system: an
artifact is generated by a model and then executed unsupervised, so the moment it changes a
human needs to be able to see what changed. Indented, unsorted JSON diffs cleanly in git --
a swapped locator or a step that became RISKY shows up as a few readable lines in a pull
request. Field order follows the model declaration order rather than being alphabetized, so the
file reads top-down the way the schema is meant to be read (identity, target, contract, steps).
"""

from __future__ import annotations

from pathlib import Path

from src.artifact.schema import Artifact


def save_artifact(artifact: Artifact, path: str | Path) -> Path:
    """Write ``artifact`` to ``path`` as indented JSON and return the path written.

    Creates parent directories so callers can write straight into a per-run evidence directory.
    Datetimes are serialized ISO-8601 by Pydantic; a trailing newline is added so the file is
    well-formed for git and for line-oriented tools.
    """
    destination = Path(path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(artifact.model_dump_json(indent=2) + "\n", encoding="utf-8")
    return destination


def load_artifact(path: str | Path) -> Artifact:
    """Read and validate the artifact at ``path``.

    Validation is not optional on load: every schema rule -- contiguous step indices, resolvable
    extracts and templates, well-formed checkpoints -- is re-checked here, so a hand-edited or
    drifted file is rejected before replay opens a browser against a live application.
    """
    return Artifact.model_validate_json(Path(path).read_text(encoding="utf-8"))
